spring.config.import=optional:file:.env[.properties]

spring.application.name=veebipood-backend

spring.datasource.url=jdbc:postgresql://dpg-dagq22ifngtc73fkl0ag-a.ohio-postgres.render.com/veebipood_m50s
spring.datasource.username=veebipood_m50s_user
spring.datasource.password=6TdvO9UZw4sa25ecISImQejvMxeTnNNP
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

smartpost.api.base-url=https://gateway.demo.posti.fi/smartpost/api/ext/v1/
smartpost.api.key=${SMARTPOST_API_KEY}
smartpost.api.gateway-secret=${SMARTPOST_GATEWAY_SECRET}

everypay.api.base-url=https://igw-demo.every-pay.com/api
everypay.api.username=${EVERYPAY_API_USERNAME}
everypay.api.password=${EVERYPAY_API_PASSWORD}
everypay.api.account-name=EUR3D1
everypay.customer-url=https://err.ee

resend.api.key=${RESEND_API_KEY}
resend.from=onboarding@resend.dev
